name: Deploy to development

on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies and Start Backend
        run: |
          npm install
          esno ./src/index.ts
        working-directory: /www/server
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
          SITE_DOMAIN: ${{ secrets.SITE_DOMAIN }}
          PASSWORD_MD5_SALT: ${{ secrets.PASSWORD_MD5_SALT }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_TSL: ${{ secrets.SMTP_TSL }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}

      - name: Build Frontend
        run: |
          npm install
          npm run build
        working-directory: /www/client
