name: Deploy to development

on:
  push:
    branches: [fallback]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Create Server Directory
        run: mkdir -p /www/wwwroot/demo-server

      - name: Install Dependencies and Start Backend
        run: |
          npm install
          esno ./src/index.ts
        working-directory: /www/wwwroot/demo-server
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
          SITE_DOMAIN: ${{ secrets.SITE_DOMAIN }}
          PASSWORD_MD5_SALT: ${{ secrets.PASSWORD_MD5_SALT }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_TSL: ${{ secrets.SMTP_TSL }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}

      - name: Create client Directory
        run: mkdir -p /www/wwwroot/demo-client

      - name: Build Frontend
        run: |
          npm install
          npm run build
        working-directory: /www/wwwroot/demo-client
